app/main/forms.py
# coding: utf8
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, FileField, TextAreaField, SelectField, SelectMultipleField, \
    FloatField, RadioField,DateField
from flask_wtf.file import FileAllowed, FileRequired
from wtforms.validators import DataRequired, ValidationError, EqualTo, Regexp
from app.models import Member, Home


class LoginForm(FlaskForm):
    """成员登录表单"""
    account = StringField(
        label="帐号",
        validators=[
            DataRequired("请输入帐号！")
        ],
        description="帐号",
        render_kw={
            "class": "form-control",
            "placeholder": "帐号",
        }
    )
    pwd = PasswordField(
        label="密码",
        validators=[
            DataRequired("请输入密码！"),
        ],
        description="密码",
        render_kw={
            "class": "form-control",
            "placeholder": "密码",
        }
    )
    submit = SubmitField(
        "登录",
        render_kw={
            "class": "btn btn-primary btn-block btn-flat",
        }
    )

    def validate_account(self, field):
        account = field.data
        member = Member.query.filter_by(account=account).count()
        if member == 0:
            raise ValidationError("帐号和密码不匹配！")


class PwdForm(FlaskForm):
    old_pwd = PasswordField(
        label="原密码",
        validators=[
            DataRequired("请输入原密码")
        ],
        description="旧密码",
        render_kw={
            "class": "form-control",
            "placeholder": "请输入原密码"
        }
    )
    new_pwd = PasswordField(
        label="新密码",
        validators=[
            DataRequired("请输入新密码")
        ],
        description="新密码",
        render_kw={
            "class": "form-control",
            "placeholder": "请输入新密码"
        }
    )
    re_pwd = PasswordField(
        label="确认密码",
        validators=[
            DataRequired("请确认新密码"),
            EqualTo("new_pwd", "两次密码输入不一致！")
        ],
        description="确认密码",
        render_kw={
            "class": "form-control",
            "placeholder": "再次输入新密码"
        }
    )
    submit = SubmitField(
        "提交",
        render_kw={
            "class": "btn btn-primary"
        }
    )

    def validate_old_pwd(self, field):
        from flask import session
        pwd = field.data
        name = session['member']
        member = Member.query.filter_by(
            account=name
        ).first()
        if not member.check_pwd(pwd):
            raise ValidationError("操作有误！")


class AddHomeForm(FlaskForm):
    """添加Home记录表单"""
    account = StringField(
        label="识别号",
        validators=[
            DataRequired("请输入识别号")
        ],
        description="identity name",
        render_kw={
            "class": "form-control",
            "placeholder": "Identity Name"
        }
    )
    nickname = StringField(
        label="Nickname",
        validators=[
            DataRequired("Please enter a nickname")
        ],
        description="nickname",
        render_kw={
            "class": "form-control",
            "placeholder": "Nick Name"
        }
    )
    net_asset = FloatField(
        label="Net Asset",
        validators=[
            DataRequired("Please enter a valid number")
        ],
        description="Net Asset",
        render_kw={
            "class": "form-control",
            "placeholder": "Net Asset"
        }
    )
    asset = FloatField(
        label="Asset",
        validators=[
            DataRequired("Please enter valid number")
        ],
        description="Asset",
        render_kw={
            "class": "form-control",
            "placeholder": "Asset"
        }
    )
    debt = FloatField(
        label="Debt",
        validators=[
            DataRequired("Please enter a valid number")
        ],
        description="Debt",
        render_kw={
            "class": "form-control",
            "placeholder": "Net Asset"
        }
    )
    cash = FloatField(
        label="Cash",
        validators=[
            DataRequired("Please enter a valid number")
        ],
        description="Cash",
        render_kw={
            "class": "form-control",
            "placeholder": "Cash"
        }
    )
    submit = SubmitField(
        "提交",
        render_kw={
            "class": "btn btn-primary"
        }
    )

    def validate_account(self, field):
        account = field.data
        home = Home.query.filter_by(account=account).count()
        if home > 0:
            raise ValidationError("Home名已存在")


class IssueDailyLogForm(FlaskForm):
    """申报项目表单"""
    category = RadioField(
        label='集体项目',
        validators=[
            DataRequired("Please pick one!")
        ],
        coerce=str,
        choices=[],
        render_kw={
            "type": "radio",
            "name ": "options",
            "autocomplete": "off",
        }
    )
    amount = FloatField(
        label="数额",
        validators=[
            DataRequired("必须输入一个数额")
        ],
        render_kw={
            "class": "form-control",
            "placeholder": "请输入数额"
        }
    )
    content = TextAreaField(
        label="备注",
        render_kw={
            "class": "form-control",
            "placeholder": "请写下简单描述, 如:买菜, 电费, 车险"
        }
    )
    submit = SubmitField(
        "提交",
        render_kw={
            "class": "btn btn-primary btn-block"
        }
    )

    def validate_type(self, field):
        type = field.data
        if type == None:
            raise ValidationError("必须选择其中一项")

class AccountEditForm(FlaskForm):
    """修改资料表单"""
    nickname = StringField(
        label="名字",
        render_kw={
            "class":"form-control",
            "placeholder":"请输入一个新名字, 留空则保持原名"
        }
    )
    mobile = StringField(
        label="手机号码",
        validators=[
            Regexp("1[3458]\\d{9}",message="手机格式不正确,请检查是否多写或少写了数字")
        ],
        description="联系号码",
        render_kw={
            "class": "form-control",
            "placeholder": "请输入11位手机号码, 留空则保持原号码不变"
        }
    )
    birthday = DateField(
        label="出生日期",
        render_kw={
            "class": "form-control",
            "placeholder": "按照 19xx-xx-xx 格式输入, 不填请留空"
        }
    )
    info = TextAreaField(
        label="个人简介",
        render_kw={
            "class": "form-control",
            "placeholder": "随意填写"
        }
    )
    face = FileField(
        label="头像",
        validators=[
            FileAllowed(['jpg','png','jpeg'],message='只能上传图片')
            # FileRequired('文件未选择')
        ],
        description="头像"
    )
    submit = SubmitField(
        "提交",
        render_kw={
            "class": "btn btn-primary btn-lg"
        }
    )

app/main/__init__.py
# coding:utf8
from flask import Blueprint

main = Blueprint("main", __name__)

import app.main.views

app/main/views.py
# coding: utf8
from . import main
from app import db, app
from flask import render_template, url_for, redirect, flash, request, session
from app.main.forms import LoginForm, PwdForm, AddHomeForm, IssueDailyLogForm, AccountEditForm
from app.models import Member, Memberlog, Home, DailyLog
from app.decorators import member_login_req
import uuid, os, datetime
from werkzeug.utils import secure_filename


def change_filename(filename):
    fileinfo = os.path.splitext(filename)
    filename = datetime.datetime.now().strftime("%Y%m%d%H%M%S") + str(uuid.uuid4().hex) + fileinfo[-1]
    return filename


@main.route("/", methods=['GET'])
@member_login_req
def home():
    return redirect(url_for("main.index", page=1))


@main.route("/<int:page>/", methods=['GET'])
@member_login_req
def index(page=None):
    if page is None:
        page = 1
    logs = DailyLog.query.order_by(
        DailyLog.addtime.desc()
    ).paginate(page=page, per_page=10)
    for item in logs.items:
        with db.session.no_autoflush:
            item.member_id = Member.query.filter_by(id=item.member_id).first().nickname

    today = datetime.datetime.now()
    costlist, incomelist = [], []
    for item in logs.items:
        if item.addtime.date() == today.date():
            costlist.append(item.amount if item.type == '支出' else 0)
            incomelist.append(item.amount if item.type == '收入' else 0)

    data = {'today':today.strftime("%Y-%m-%d %A"), 'income': sum(incomelist), 'cost': sum(costlist)}
    return render_template("main/index.html", logs=logs, data=data)


@main.route("/login/", methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if "member" in session and "member_id" in session:
        flash("你已登录，请不要重复登录", "err")
        return redirect(request.args.get("next") or url_for("main.home"))
    if form.validate_on_submit():
        data = form.data
        member = Member.query.filter_by(account=data["account"]).first()
        if not member.check_pwd(data['pwd']):
            flash("账户和密码不匹配", "err")
            return redirect(url_for("main.login"))
        session["member"] = data["account"]
        session["member_id"] = member.id
        memberlog = Memberlog(
            member_id=member.id,
            ip=request.remote_addr
        )
        db.session.add(memberlog)
        db.session.commit()
        flash("登录成功！", "ok")
        flash("online", "mem1")
        return redirect(request.args.get("next") or url_for("main.home"))
    return render_template("main/login.html", form=form)


@main.route("/logout", methods=['GET'])
def logout():
    if '_flashes' in session:
        msg = session['_flashes']
        session.clear()
        session['_flashes'] = msg
    else:
        session.clear()
    flash("You've logged out.", "ok")
    return redirect(url_for('main.login'))


@main.route("/account/<int:id>", methods=['GET', 'POST'])
@member_login_req
def account(id=None):
    data = {}
    if id == None:
        id = int(session['member_id'])
    try:
        member = Member.query.filter_by(account=session['member']).first()
        last_memberlogin = member.memberlogs[-1]
        data = {
            'nickname': member.nickname,
            'last_login': last_memberlogin.addtime,
            'ip': last_memberlogin.ip,
            'face': member.face
        }
        dailylogs = [*member.dailylogs]
        dailylogs.reverse()

    except BaseException as e:
        flash(e, "err")
    form1 = PwdForm()
    if form1.validate_on_submit():
        from werkzeug.security import generate_password_hash
        member.pwd = generate_password_hash(form1.data['new_pwd'])
        db.session.add(member)
        db.session.commit()
        flash("修改密码成功，请重新登录！", "ok")
        return redirect(url_for("main.logout"))

    #
    # 预留form2给其他修改表单，例如编辑信息，增删查改记录
    #
    return render_template("main/account.html", id=id, form1=form1, data=data, dailylogs=dailylogs)


@main.route("/account_edit/<int:id>", methods=['GET', 'POST'])
@member_login_req
def account_edit(id):
    member = Member.query.get_or_404(int(id))
    form = AccountEditForm()
    # form.face.validators=[]
    if request.method == 'GET':
        form.nickname.data = member.nickname
        form.mobile.data = member.mobile
        form.birthday.data = member.birthday
        form.info.data = member.info
    if form.validate_on_submit():
        data = form.data

        if form.face.data:
            file_url = secure_filename(form.face.data.filename)
            oldface = member.face
            member.face = change_filename(file_url)
            form.face.data.save(app.config['MEM_DIR'] + member.face)

        member.nickname = data['nickname']
        member.mobile = data['mobile']
        member.info = data['info']
        member.birthday = data['birthday']

        try:
            db.session.add(member)
            db.session.commit()
        except BaseException:
            db.session.roll()
            flash("Errors!", "err")
            return redirect(url_for("main.account_eidt", id=id))
        flash("Edit done", "ok")
        os.renames(app.config['MEM_DIR']+oldface, app.config['MEM_DIR']+'abandoned-'+oldface)
        return redirect(url_for("main.account", id=id))
    return render_template("main/account_edit.html", form=form, id=id)


@main.route("/database/", methods=['GET', 'POST'])
@member_login_req
def database():
    form = AddHomeForm()
    home = Home.query.order_by(Home.id.desc()).first()
    from app.charts import home_basic
    homechart = home_basic(home)

    if form.validate_on_submit():
        data = form.data
        new_home = Home(
            account=data['account'],
            nickname=data['nickname'],
            net_asset=data['net_asset'],
            asset=data['asset'],
            debt=data['debt'],
            cash=data['cash']
        )
        try:
            db.session.add(new_home)
            db.session.commit()
        except BaseException:
            db.session.rollback()
            flash("Error", "err")
            return redirect(url_for('main.database'))
        flash("Add Home Success", "ok")
        return redirect(url_for("main.database"))
    return render_template("main/database.html", form=form, myechart=homechart)


@main.route("/issueclaim", methods=['GET', 'POST'])
@member_login_req
def issueclaim():
    form = IssueDailyLogForm()
    cateset = ["食物", "杂费", "家居", "传统", "节庆", "车辆", "出行",
               "健康", "消费", "宠物", "旅游", "其他", "亲戚", "其他"]
    sets = [(x, x) for x in cateset]
    form.category.choices = sets
    subsets = [_ for _ in form.category]
    if form.validate_on_submit():
        data = form.data
        dailylog = DailyLog(
            uuid=uuid.uuid4().hex,
            type='支出',
            category=data['category'],
            amount=data['amount'],
            member_id=session['member_id'],
            content=data['content'],
            status='pending'
        )
        try:
            db.session.add(dailylog)
            db.session.commit()
        except BaseException as e:
            print(e)
            db.session.rollback()
            flash("出错了!请重试!", "err")
            return redirect(url_for("main.issueclaim"))
        flash("添加成功", "ok")
        return redirect(url_for("main.home"))
    return render_template("main/issueclaim.html", form=form, subsets=subsets)


@main.route("/issueincome/", methods=['GET', 'POST'])
@member_login_req
def issueincome():
    form = IssueDailyLogForm()
    sets = [("月度剩余", "月度剩余"), ("工资转入", "工资转入"), ("企业转入", "企业转入")]
    form.category.choices = sets
    subsets = [_ for _ in form.category]
    if form.validate_on_submit():
        data = form.data
        dailylog = DailyLog(
            uuid=uuid.uuid4().hex,
            type="收入",
            category=data['category'],
            amount=data['amount'],
            member_id=session['member_id'],
            content=data['content'],
            status='pending'
        )
        try:
            db.session.add(dailylog)
            db.session.commit()
        except BaseException as e:
            print(e)
            db.session.rollback()
            flash("出错了!请重试!", "err")
            return redirect(url_for("main.issueincome"))
        flash("添加成功", "ok")
        return redirect(url_for("main.home"))
    return render_template("main/issueincome.html", form=form, subsets=subsets)


@main.route("/memberlist/<int:page>/", methods=['GET', 'POST'])
@member_login_req
def memberlist(page=None):
    if page == None:
        page = 1
    page_data = Member.query.order_by(
        Member.id
    ).paginate(page=page, per_page=6)
    return render_template('main/memberlist.html', page_data=page_data)


@main.route("/memberdetail/<int:id>/", methods=['GET', 'POST'])
@member_login_req
def memberdetail(id=None):
    if id == None:
        id = 1
    member = Member.query.filter_by(id=id).first()
    member.pwd = ""
    return render_template('main/memberdetail.html', id=id, member=member)


@main.route("/log_detail/<int:id>", methods=['GET'])
@member_login_req
def log_detail(id=None):
    if id == None:
        id = 1
    log = DailyLog.query.filter_by(id=id).first()
    log.test = Member.query.filter_by(id=log.member_id).first().nickname
    return render_template("main/log_detail.html", id=id, log=log)


@main.route("/log_del/<int:id>/", methods=['GET'])
@member_login_req
def log_del(id=None):
    auth = DailyLog.query.filter_by(id=id).first().member_id
    if id == None:
        flash("错误链接", "err")
        return redirect(url_for("main.home"))
    elif session['member_id'] != auth:
        flash("你没有权限", "err")
        return redirect(url_for("main.home"))
    flash("ok", "ok")
    return redirect(url_for("main.home"))

app/templates/main/account.html
{% extends "ui/mainbase.html" %}
{% block title %} 个人信息 {% endblock %}
{% block css %}
    <style>
        .myaccount-row {
            background: #ffffff;
        }

        .mylogoinfo {
            box-shadow: 0 3px 5px 3px #ebf2ff;
            height: 100%;
            margin-bottom: 9px;
            padding: 0px;
        }

        #mylogo {
            margin: auto;
            position: relative;
            display: block;
            padding: 10px;
            height: 100%;
        }
        .info-div {
            padding: 0px;
        }

        .info-content {
            padding: 15px;
            border-left: 1px solid #dddddd;
            border-bottom: 1px solid #dddddd;
            border-right: 1px solid #dddddd;
        }
    </style>
{% endblock %}

{% block sidebar %}{% include "ui/mainsidebar.html" %}{% endblock %}
{% block main %}
    <!--捕捉修改密码表单的错误信息，显示模态框-->
    {% if form1.re_pwd.errors or form1.new_pwd.errors or form1.old_pwd.errors %}
        <script>
            $(function () {
                $('#my1stModal').modal(
                    'show'
                )
            });
        </script>
    {% endif %}
    <!--错误消息捕捉-->

    <!--Main-->
    <div class="col-lg-10 col-md-10 col-sm-12 col-xs-12" style="padding:0px;">
        <section>
            <!-- 1s Row -->
            <div class="row myaccount-row">
                <!--1s Col-->
                <div class="col-md-4 col-lg-4 col-xs-12 col-sm-12 mylogoinfo">
                    <!--头像-->
                    <div style="width:100%;height:200px;">
                        <img id="mylogo"
                             src="{{ url_for('static',filename='uploads/members/'+data.face) }}" alt="">
                    </div><!--头像-->
                </div><!--1st col-->
                <!-- 2nd Col -->
                <div class="col-md-8 col-lg-6 col-xs-12 col-sm-12 mylogoinfo" style="float: left; height: 100%;">
                    <div class="col-xs-12 col-lg-9 col-md-9" style="padding: 15px;">
                        <div style="float:left;text-align: right;width: 30%;">
                            <p><strong>成员:</strong></p>
                            <p><strong>最近登录:</strong></p>
                            <p><strong>登录位置:</strong></p>
                        </div>
                        <div style="float: left;text-align: left;70%; padding-left: 15px;">
                            <p>{{ data.nickname }}</p>
                            <p>{{ data.last_login }}</p>
                            <p>{{ data.ip }}</p>
                        </div>
                    </div>

                    <div class="hidden-xs hidden-sm col-lg-3 col-md-3" style="height: 200px; padding: 10px;">
                        <div>
                            {#                            <a href="#" data-toggle="modal" data-target="#my1stModal">修改密码</a>#}
                            {#                            <a href="{{ url_for("main.account_edit", id=session['member_id']) }}">编辑信息</a>#}
                            <a class="btn btn-default" role="button"
                               href="{{ url_for("main.account_edit", id=session['member_id']) }}">编辑信息</a>
                            <a class="btn btn-default" role="button" href="#" data-toggle="modal"
                               data-target="#my1stModal">修改密码</a>
                        </div>
                    </div>

                    <!--折叠栏-->
                    <div class="col-xs-12" style="height: 100%; padding:0px;">
                        <div class="panel-group hidden-md hidden-lg" role="tablist" style="margin-bottom: 0px;">
                            <div class="panel panel-default">
                                <div class="panel-heading" role="tab" id="collapseListGroupHeading1"
                                     style="text-align: center">
                                    <h4 class="panel-title">
                                        <a class="" role="button" data-toggle="collapse" href="#collapseListGroup1"
                                           aria-expanded="true"
                                           aria-controls="collapseListGroup1">
                                            编辑信息
                                        </a>
                                    </h4>
                                </div>
                                <div id="collapseListGroup1" class="panel-collapse collapse" role="tabpanel"
                                     aria-labelledby="collapseListGroupHeading1" aria-expanded="true" style="">
                                    <ul class="list-group">
                                        <li class="list-group-item"><a
                                                href="{{ url_for("main.account_edit",id=session['member_id']) }}">编辑个人信息</a>
                                        </li>
                                        <li class="list-group-item"><a href="#" data-toggle="modal"
                                                                       data-target="#my1stModal">修改密码</a>
                                        </li>
                                        <li class="list-group-item"><a href="#">等待修改</a></li>
                                    </ul>
                                    <div class="panel-footer">
                                        <span class="glyphicon glyphicon-menu-up"></span>
                                        <a href="#collapseListGroup1" data-toggle="collapse" style="color: black">收起</a>
                                    </div>
                                </div><!--折叠栏列表-->
                            </div>
                        </div><!--折叠栏--></div>
                </div><!--2nd Col-->
            </div><!--1st ROW-->
            <!-- 2nd Row -->
            <div class="row">
                <div class="col-md-12 col-lg-10 col-xs-12 info-div">
                    <ul id="mytab" class="nav nav-tabs">
                        <li class="active"><a href="#content1" data-toggle="tab">最近活动</a></li>
                        <li><a href="#content2" data-toggle="tab">活动日历</a></li>
                        <li><a href="#content3" data-toggle="tab">Verbose Log</a></li>
                    </ul>
                    <div id="myTabContent" class="tab-content info-content">
                        <div class="tab-pane fade in active" id="content1">
                            <table class="table table-hover" style="margin-bottom: 0px">
                                <thead>
                                <tr>
                                    <th>状态</th>
                                    <th>日期</th>
                                    <th>数额</th>
                                    <th>类型/项目</th>
                                    {#                                        <th>备注</th>#}
                                    {#                                        <th>选项</th>#}
                                </tr>
                                </thead>
                                <tbody>
                                {% for log in dailylogs %}
                                    {% if loop.index < 10 %}
                                        <tr style="font-size: 18px;" onclick="get_detail({{ log.id }})" data-toggle="modal" data-target="#logModal">
                                            <td>{{ log.status }}</td>
                                            <td>{{ log.addtime.strftime('%m-%d') }}</td>
                                            <td>{{ log.amount }}</td>
                                            <td>
                                                {% if log.type == '收入' %}
                                                    <a href="#" class="label label-success">{{ log.type }}</a>
                                                {% else %}
                                                    <a href="#" class="label label-default">{{ log.type }}</a>
                                                {% endif %}
                                                /{{ log.category }}
                                            </td>
                                        </tr>
                                    {% endif %}
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                        <div class="tab-pane" id="content2"><p>Insert Calender</p></div>
                        <div class="tab-pane" id="content2"><p>Insert verbose log</p></div>
                    </div>
                </div>
            </div><!--2nd ROW-->
        </section>
    </div>

    <!-- my1stModal -->
    <form class="form-group" role="form" method="POST">
        <div class="modal fade" id="my1stModal" data-backdrop="static" tabindex="-1" role="dialog"
             aria-labelledby="my1stModalLabel" style="margin-top: 60px;">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button data-dismiss="modal" class="close" type="button"><span
                                aria-hidden="true">×</span><span class="sr-only">Close</span></button>
                        <h4 class="modal-title">修改密码</h4>
                    </div>

                    <div class="modal-body">
                        <div class="form-group has-feedback">
                            <label for="input_oldpwd">{{ form1.old_pwd.label }}</label>
                            {{ form1.old_pwd }}
                            {% for err in form1.old_pwd.errors %}
                                <div class="col-md-12">
                                    <p style="color: red">{{ err }}</p>
                                </div>
                            {% endfor %}
                        </div>
                        <div class="form-group">
                            <label for="input_newpwd">{{ form1.new_pwd.label }}</label>
                            {{ form1.new_pwd }}
                            {% for err in form1.new_pwd.errors %}
                                <div class="col-md-12">
                                    <p style="color: red">{{ err }}</p>
                                </div>
                            {% endfor %}
                        </div>
                        <div class="form-group">
                            <label for="input_repwd">{{ form1.re_pwd.label }}</label>
                            {{ form1.re_pwd }}
                            {% for err in form1.re_pwd.errors %}
                                <div class="col-md-12">
                                    <p style="color: red">{{ err }}</p>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button data-dismiss="modal" class="btn btn-default" type="button">关闭</button>
                        {{ form1.csrf_token }}
                        {{ form1.submit }}
                    </div>
                </div><!-- /.modal-content -->
            </div><!-- /.modal-dialog -->
        </div><!--my1stModal-->
    </form>

    <div class="modal fade" id="logModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
         style="margin-top: 30px; ">
        <div class="modal-dialog">
            <div class="modal-content" id="m-1"></div><!-- /.modal-content -->
        </div>
    </div><!-- /.modal-dialog -->
{% endblock %}
{% block script %}
    <script>
        function get_detail(id) {
            $("#m-1").load("/log_detail/" + id)
        }

        $(document).ready(function () {
            $("#n-2").addClass("active");
            $("#bn-3").addClass("active");
        });
    </script>
{% endblock %}

app/templates/main/log_detail.html
<div class="modal-body">
    <div class="row" style="padding-left: 15px; font-size: 18px;">
        <p><b>编号:</b> {{ log.id }}</p>
        <p><b>UUID:</b> {{ log.uuid }}</p>
        <hr>
        <p><b>类型 / 项目</b></p>
        <a class="btn btn-default">{{ log.type }}</a> /
        <a class="btn btn-default">{{ log.category }}</a>
        <hr>
        <p><b>成员:</b> {{ log.test }}</p>
        <p><b>数额:</b> {{ log.amount }} 元</p>
        <p><b>日期:</b> {{ log.addtime }}</p>
        <p><b>状态:</b> {{ log.status }}</p>
        <hr>
        <p><b>详细描述:</b></p>
        <div style="font-size: 14px;"><p>{{ log.content }}</p></div>
    </div>
</div>
<div class="modal-footer" style="text-align: center">
    <button data-dismiss="modal" class="btn btn-default" type="button">关闭</button>
    {% if log.member_id == session['member_id'] %}
        <button class="btn btn-primary" type="button">编辑</button>
        <a class="btn btn-danger" role="button" href="{{ url_for("main.log_del", id=log.id) }}">删除</a>
    {% endif %}
</div>

app/templates/main/login.html
{% extends 'ui/mainbase.html' %}
{% block title %}成员登录{% endblock %}

{% block css %}{% endblock %}
{% block sidebar %}{% endblock %}

{% block main %}
    {#      登录表单#}
    <div class="row">
        <div class="col-xs-10 col-sm-10 col-md-6 col-lg-4 col-lg-offset-4 col-md-offset-3 col-xs-offset-1 col-sm-offset-1">
            <!--表单内核-->
            <form class="form-signin" method="post">
                <h2 class="form-signin-heading">登录</h2>
                <div class="form-group has-feedback">
                    {{ form.account }}
                    <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
                    {% for err in form.account.errors %}
                        <div class="col-md-12">
                            <p style="color: red">{{ err }}</p>
                        </div>
                    {% endfor %}
                </div>
                <div class="form-group has-feedback">
                    {{ form.pwd }}
                    <span class="glyphicon glyphicon-lock form-control-feedback"></span>
                    {% for err in form.pwd.errors %}
                        <div class="col-md-12">
                            <p style="color: red">{{ err }}</p>
                        </div>
                    {% endfor %}
                </div>
                <div class="row">
                    <div class="col-xs-8">
                    </div>
                    <div class="col-xs-4">
                        {{ form.submit }}
                        {{ form.csrf_token }}
                    </div>
                </div>
            </form>
            <!-- 表单内核-->
        </div>
    </div>
    {#      登录表单#}
{% endblock %}
{% block script %}{% endblock %}

app/templates/main/pwd.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>